Load dataset and preprocess it based on preprocessing.Rmd
```{r}
dataset <- read.csv("College.csv")

dataset_cleared <- dataset
dataset_cleared$Accept <- NULL # <- dataset_cleared$Accept <- dataset_cleared$Enroll <- NULL
dataset_cleared$Enroll <- NULL
dataset_cleared$X <- NULL
dataset_cleared$Apps <- NULL

normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

dataset_cleared[ , 2:ncol(dataset_cleared)] <- lapply(dataset_cleared[ , 2:ncol(dataset_cleared)], normalize)


dataset_cleared$Private <- as.factor(dataset_cleared$Private)

dataset_cleared$Private <- as.numeric(dataset_cleared$Private) - 1
```

Try a glm with all the usable parameters:

```{r}

glm_all_parameters <- glm(dataset$Apps ~ .,data=dataset_cleared, family=poisson)

#private <- glm(dataset$Apps ~ dataset_cleared$Private,data=dataset_cleared, family=poisson)
#summary(private)

#undergrad <- glm(dataset$Apps ~ dataset_cleared$F.Undergrad,data=dataset_cleared, family=poisson)
#summary(undergrad)

#undergradPrivate <- glm(dataset$Apps ~ dataset_cleared$F.Undergrad + dataset_cleared$Private,data=dataset_cleared, family=poisson)
#summary(undergradPrivate)

summary(glm_all_parameters)

```

Personal is not significant and as told in preprocessing.Rmd we should remove Top10perc and PhD too.

```{r}

dataset_cleared$Top10perc <- NULL
dataset_cleared$PhD <- NULL

clearedFromVariables <- glm(dataset$Apps ~ .,data=dataset_cleared, family=poisson)

summary(clearedFromVariables)

dataset_cleared$Personal <- NULL
# Books is almost useless, we should motivate a reason to remove it.
#dataset_cleared$Books <- NULL

# Calculate the number of training lines (80% of the dataset)
n_training_lines <- floor(0.8 * nrow(dataset_cleared))

# Ensure the number of training lines is even
if (n_training_lines %% 2 != 0) {
  n_training_lines <- n_training_lines - 1
}


# save index of lines with Private 1 and lines with Private 0
index_dataset_public <- which(dataset_cleared$Private == 0)

index_dataset_private <- which(dataset_cleared$Private == 1)

# Calculate the exact percentage of private 1 lines in the dataset
percentage_private <- length(index_dataset_private) / nrow(dataset_cleared)

# take 80% of lines from index_dataset_public
train_index_dataset_public <- sample(index_dataset_public, floor(n_training_lines * (1 - percentage_private)))
train_index_dataset_private <- sample(index_dataset_private, floor(n_training_lines * (percentage_private)))

# Cobine the two train_index_dataset_ into train_index
train_index <- c(train_index_dataset_public, train_index_dataset_private)


train_data <- dataset_cleared[train_index,]
test_data <- dataset_cleared[-train_index,]


glm_model <- glm(dataset$Apps[train_index] ~ .,data=train_data, family=poisson)

summary(glm_model)

summary(glm(dataset$Apps ~ .,data=dataset_cleared, family=poisson))

  <- predict.glm(glm_model, newdata = test_data)
#private -> 1934025
#undergrad -> 1074621
#undergradPrivate -> 1062182
#clearedFromVariablesWithBooks -> 549073
#clearedFromVariables -> 554278



```
